version: "3"
services:
  proxy:
    image: nginx
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7070:80"
  ui:
    build:
      context: ./client
    ports:
      - "8080:8080"
  node-server:
    build:
      context: ./server
    ports:
      - "3000:3000"
