POST http://localhost:3000/api/auth/sign-up
content-type: application/json

{
    "username":"mateusz",
    "email":"mateusz14@ateusz.com",
    "password":"12345"
}
###
POST http://localhost:3000/api/kids/addkid
content-type: application/json

{
    "name":"mateusz",
    "dateOfBirth":"01-01-2012",
    "height":120,
    "weight":25,
    "gender":"female",
    "height":120
}

###
GET http://localhost:3000/api/users
Content-Type: application/json

###
GET http://localhost:3000/api/users/621e8cb924b74f4dd1952d44
Content-Type: application/json

### all kids for a user 
GET http://localhost:3000/api/users/621e8cb924b74f4dd1952d44/kids
Content-Type: application/json

### get one kid 
GET http://localhost:3000/api/users/621e8cb924b74f4dd1952d44/kids/621f7825eff8eac9bfda2345
Content-Type: application/json

### delete kid for a user 
DELETE http://localhost:3000/api/users/621e8cb924b74f4dd1952d44/kids/621f7825eff8eac9bfda2345
Content-Type: application/json

### update kid for a user
PUT http://localhost:3000/api/users/621e8cb924b74f4dd1952d44/kids/621f7825eff8eac9bfda2345
Content-Type: application/json

{
    "name":"lolek***33",
    "dateOfBirth":"01-01-2013",
    "height":1,
    "weight":2,
    "gender":"male"
}

### add kid for a user
POST http://localhost:3000/api/users/621e8cb924b74f4dd1952d44/kids
content-type: application/json

{
    "name":"lolek",
    "dateOfBirth":"01-01-2013",
    "height":13,
    "weight":132,
    "gender":"male"
}

